use_frameworks!

target 'HJPodTestLibA_Example' do
  pod 'HJPodTestLibA', :path => '../'

  target 'HJPodTestLibA_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
